### ISSUE TITLE
hello after the program runs around 7-10 times it provides me with this error from the api

### ISSUE THREAD

**Issue by FaresKaranib** [Jackhammer9/RedDownloader#42]
Traceback (most recent call last):
  File "C:\Users\fares\Desktop\Instagram WeakerLimes\Main(Working).py", line 124, in <module>
    Upload(counter,AmountCounter,posted_authors)
  File "C:\Users\fares\Desktop\Instagram WeakerLimes\Main(Working).py", line 99, in Upload
    author = GetMeme(subreddits)
  File "C:\Users\fares\Desktop\Instagram WeakerLimes\Main(Working).py", line 50, in GetMeme
    author = post.GetPostAuthors()[0]
  File "C:\Users\fares\AppData\Local\Programs\Python\Python38\lib\site-packages\RedDownloader\RedDownloader.py", line 701, in GetPostAuthors
    for author in self.ProcessedLinks:
AttributeError: 'DownloadImagesBySubreddit' object has no attribute 'ProcessedLinks'
Traceback (most recent call last):
  File "C:\Users\fares\Desktop\Instagram WeakerLimes\Main(Working).py", line 129, in <module>
    Upload(counter,AmountCounter,posted_authors)
  File "C:\Users\fares\Desktop\Instagram WeakerLimes\Main(Working).py", line 99, in Upload
    author = GetMeme(subreddits)
  File "C:\Users\fares\Desktop\Instagram WeakerLimes\Main(Working).py", line 50, in GetMeme
    author = post.GetPostAuthors()[0]
  File "C:\Users\fares\AppData\Local\Programs\Python\Python38\lib\site-packages\RedDownloader\RedDownloader.py", line 701, in GetPostAuthors
    for author in self.ProcessedLinks:
AttributeError: 'DownloadImagesBySubreddit' object has no attribute 'ProcessedLinks'
Traceback (most recent call last):
  File "C:\Users\fares\Desktop\Instagram WeakerLimes\Main(Working).py", line 129, in <module>
    Upload(counter,AmountCounter,posted_authors)
  File "C:\Users\fares\Desktop\Instagram WeakerLimes\Main(Working).py", line 99, in Upload
    author = GetMeme(subreddits)
  File "C:\Users\fares\Desktop\Instagram WeakerLimes\Main(Working).py", line 50, in GetMeme
    author = post.GetPostAuthors()[0]
  File "C:\Users\fares\AppData\Local\Programs\Python\Python38\lib\site-packages\RedDownloader\RedDownloader.py", line 701, in GetPostAuthors
    for author in self.ProcessedLinks:
AttributeError: 'DownloadImagesBySubreddit' object has no attribute 'ProcessedLinks'

**Comment by Jackhammer9** [comment]
Hello there,

Can you provide an example code that is resulting in this issue? 

Thanks

**Comment by FaresKaranib** [comment]
my program is private but if you can provide your email I can share it with you however the main issue is saying that the attribute proccessedlinks has not attribute and this is happening when the prompt author = post.GetPostAuthors()[0] is being used multiple times

**Comment by FaresKaranib** [comment]
ive tried many things and its clear to me that there's a certain error that occurs from your API when the DownloadImagesBySubreddit is called which leads to an error with smthn to do called processed links. id appreciate a fix

**Comment by Jackhammer9** [comment]
I am currently checking out the issue will update this issue as and when i am able to debug. Thank you for your patience.
